version: '3.1'
services:
  database:
    container_name: api_database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER : ${DATABASE_USER:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-root}
      POSTGRES_DB: ${DATABASE_NAME:-db_java}
    ports:
      - "5432:5432"
