INSERT INTO categorie (id, nom_categorie) VALUES (1, 'Guerre');
INSERT INTO categorie (id, nom_categorie) VALUES (2, 'Mario');
INSERT INTO categorie (id, nom_categorie) VALUES (3, 'Pain');
INSERT INTO categorie (id, nom_categorie) VALUES (4, 'Logo');

INSERT INTO choix (id, categorie_id, description) VALUES (1, 1, '1ère guerre mondiale');
INSERT INTO choix (id, categorie_id, description) VALUES (2, 1, '2ème guerre mondiale');
INSERT INTO choix (id, categorie_id, description) VALUES (3, 1, 'guerre corée');
INSERT INTO choix (id, categorie_id, description) VALUES (4, 1, 'guerre vietnam');
INSERT INTO choix (id, categorie_id, description) VALUES (5, 2, 'Mario galaxy');
INSERT INTO choix (id, categorie_id, description) VALUES (6, 2, 'mario kart');
INSERT INTO choix (id, categorie_id, description) VALUES (7, 2, 'mario bros wander');
INSERT INTO choix (id, categorie_id, description) VALUES (8, 2, 'New Super Mario Bros');
INSERT INTO choix (id, categorie_id, description) VALUES (9, 3, 'pain de seigle');
INSERT INTO choix (id, categorie_id, description) VALUES (10, 3, 'Pain couronne bordelaise');
INSERT INTO choix (id, categorie_id, description) VALUES (11, 3, 'Pain couronne lyonnaise');
INSERT INTO choix (id, categorie_id, description) VALUES (12, 3, 'pain au levain');
INSERT INTO choix (id, categorie_id, description) VALUES (13, 3, 'pain méteil');
INSERT INTO choix (id, categorie_id, description) VALUES (14, 4, 'Takima');
INSERT INTO choix (id, categorie_id, description) VALUES (15, 4, 'Capgemini');
INSERT INTO choix (id, categorie_id, description) VALUES (16, 4, 'jeux olympique');
INSERT INTO choix (id, categorie_id, description) VALUES (17, 4, 'Sopra Steria');
UPDATE choix SET image = ('https://pixabay.com/fr/images/search/guerre/') WHERE id=1;